### ISSUE TITLE
Segfault when format_out leads to empty out

### ISSUE THREAD

**Issue by nheir** [archlinuxfr/package-query#107]
Step to reproduce:
  `package-query -Qs firefox -f "%t"`
or 
`package-query -Qs firefox -f ""`

That issue is rare  but it's a segfault after all.

It comes from util.c, string_t.s is NULL as long as there is nothing to add (including empty string). Then pkg_to_str return NULL instead of empty string and print_package doesn't handle it.

**Comment by f2404** [comment]
@nheir Thanks for the report! I'll get it handled.

**Comment by f2404** [comment]
Fixed via https://github.com/archlinuxfr/package-query/commit/2f38ab09e859045287a3f136792cfcbe096f5eaf
