### ISSUE TITLE
AUR v1 rpc api broken

### ISSUE THREAD

**Issue by Skunnyk** [archlinuxfr/package-query#108]
Well, I think that we need to release a new version of package-query.
Since this morning, the "old" api seems broken : https://aur.archlinux.org/rpc.php?type=search&arg=yaourt

Fortunally, package-query-git now support rpc v=5 and works

**Comment by f2404** [comment]
I fully agree! Let's release it! :)

**Comment by f2404** [comment]
@Skunnyk Could you please also update PKGBUILDs for AUR packages? Dependency should be updated to `pacman>=5.0`.

**Comment by f2404** [comment]
I guess we can close this?
