### ISSUE TITLE
Support querying AUR git URL

### ISSUE THREAD

**Issue by yan12125** [archlinuxfr/package-query#11]
'%u' allows me to query the package tarball url:
```
$ package-query --aur-url "https://aur4.archlinux.org" -Aif "%u" yaourt 
https://aur4.archlinux.org/cgit/aur.git/snapshot/yaourt.tar.gz
```

Is it possible to query the git URL? For example:
```
$ package-query --aur-url "https://aur4.archlinux.org" -Aif "%g" yaourt 
https://aur4.archlinux.org/yaourt.git/
```

"%g" is just my naive intuition. (**g**it)

**Comment by Skunnyk** [comment]
Yup, good idea, I'll look at it (or you can provide a patch if you are motivated :))

**Comment by Skunnyk** [comment]
Implemented in #15

**Comment by Skunnyk** [comment]
oh god,"g" is already used for "group" in https://github.com/archlinuxfr/package-query/blob/master/src/util.c#L768 :|

That's why package-query -SsA aurpackage displays git urls…

<pre>
$ package-query -SsA xcfa 
aur/xcfa 5.0.2-2 (https://aur.archlinux.org/xcfa.git) (39)
    X Convert File Audio
aur/xcfa_cli 0.0.7-3 (https://aur.archlinux.org/xcfa_cli.git) (2)
    Audio Files Conversion - CLI version
</pre>

So, maybe %G ?

**Comment by yan12125** [comment]
Sorry for the mistake. ```%G``` should be a good idea. By the way, could you update [package-query.8](https://github.com/archlinuxfr/package-query/blob/master/doc/package-query.8#L216-L242)? I didn't see ```%g``` there so I choose it...

**Comment by Skunnyk** [comment]
Fixed in https://github.com/archlinuxfr/package-query/commit/930577896e08eb98e0cc8e08486b963b34374050

I added %G in man. 
Hm, %g is only used when query alpm database and not aur, you can't use it directly in -f

**Comment by yan12125** [comment]
OK. How about add a section for symbols used internally only? That prevents conflicts.

**Comment by yan12125** [comment]
This feature is implemented correctly now. The doc is another problem so I think this issue can be closed now.
