### ISSUE TITLE
/usr/lib/yaourt/util.sh 

### ISSUE THREAD

**Issue by dtschmitz** [archlinuxfr/package-query#110]
Hi Folks,

Hey thanks for all your timely hard work on this project.

Listen, I am stuck 'in the middle' on an issue which I believe is not yours but one belonging to the Antergos Linux Devs.

It comes down to this: Pamac, the gui software updater, calls the yaourt wrapper which calls /usr/lib/yaourt/util.sh, which invokes package-query at line 190 with the following error:

http://i.imgur.com/UwQvIac.png

and then does a core dump.

From my vantage point, it would appear that your command tail args have changed in 1.8, yes?

If so, then, util.sh needs to pass into package-query the appropriate args, yes?

Arghhhhhhhhhhhh.  

Seriously, could I have your opinion on this issue?

Many thanks 
Kindest Regards,
Dietrich
dietrich@dtschmitz.com

[util.sh.txt](https://github.com/archlinuxfr/package-query/files/162161/util.sh.txt)

**Comment by larchunix** [comment]
We had a similar report on yaourt side (https://github.com/archlinuxfr/yaourt/issues/154#issuecomment-191268635).

Did you compile package-query from AUR or did you install it from archlinuxfr repository ?

**Comment by karasu** [comment]
>Listen, I am stuck 'in the middle' on an issue which I believe is not yours but one belonging to the Antergos Linux Devs.

We do not develop Pamac. It's a software developed by Manjaro.

**Comment by f2404** [comment]
@dtschmitz Have you tried `package-query-git`? It could help resolve the issue.

**Comment by dtschmitz** [comment]
Hi, I am all set SOLVED.  Thanks for the reply.  -- Dietrich

**Comment by dtschmitz** [comment]
closing
