### ISSUE TITLE
The URL https://www.archlinux.org/packages/(null)/(null)/(null)/json/ returned error : 404

### ISSUE THREAD

**Issue by FadeMind** [archlinuxfr/package-query#127]
Commit https://github.com/archlinuxfr/package-query/commit/b8c322a48074ac36716c477138a7302c3331da17 DON'T have this issue.

Some one of recent commits give in results at the end `The URL https://www.archlinux.org/packages/(null)/(null)/(null)/json/ returned error : 404`

```
[tomasz@arch ~]$ export LANG=C
[tomasz@arch ~]$ yaourt -Syua --noconfirm
:: Synchronizing package databases...
 kde-unstable is up to date
 testing is up to date
 core is up to date
 extra is up to date
 community-testing is up to date
 community is up to date
 multilib-testing is up to date
 multilib is up to date
 infinality-bundle is up to date
 infinality-bundle-multilib is up to date
 infinality-bundle-fonts is up to date
 repo-ck is up to date
 atom is up to date
 xyne-x86_64 is up to date
The URL https://www.archlinux.org/packages/(null)/(null)/(null)/json/ returned error : 404
The URL https://www.archlinux.org/packages/(null)/(null)/(null)/json/ returned error : 404
The URL https://www.archlinux.org/packages/(null)/(null)/(null)/json/ returned error : 404
The URL https://www.archlinux.org/packages/(null)/(null)/(null)/json/ returned error : 404
The URL https://www.archlinux.org/packages/(null)/(null)/(null)/json/ returned error : 404
The URL https://www.archlinux.org/packages/(null)/(null)/(null)/json/ returned error : 404
The URL https://www.archlinux.org/packages/(null)/(null)/(null)/json/ returned error : 404
The URL https://www.archlinux.org/packages/(null)/(null)/(null)/json/ returned error : 404
The URL https://www.archlinux.org/packages/(null)/(null)/(null)/json/ returned error : 404
The URL https://www.archlinux.org/packages/(null)/(null)/(null)/json/ returned error : 404
 Foreign packages: \ 183 / 183
[tomasz@arch ~]$ 
```

@f2404

**Comment by f2404** [comment]
Thanks for reporting this, I will take a look.

**Comment by f2404** [comment]
@FadeMind The latest commit should fix it - could you please try?

I was not able to reproduce the issue though. Do you have any non-default yaourt settings?

**Comment by FadeMind** [comment]
@f2404 Commit https://github.com/archlinuxfr/package-query/commit/448d0b263792a2459138cd290ed203b48d560117
FIXED issue. Thanks.

**Comment by FadeMind** [comment]
@f2404 see config code in my above post

**Comment by f2404** [comment]
Thanks. The config doesn't look unusual.
Do you have any packages built locally - not installed from AUR? I mean, it seems you have 183 unofficial packages installed but only 10 of them produced the error so they should be somehow different from others.

**Comment by FadeMind** [comment]
packages from AUR and build localy from `pacman -Qqem > pkglist-aur.txt`: 
[pkglist-aur.txt](https://github.com/archlinuxfr/package-query/files/274503/pkglist-aur.txt)

**Comment by f2404** [comment]
I think the packages from the external repos could case the issue...
