### ISSUE TITLE
Foreign packages: \ NN / NN

### ISSUE THREAD

**Issue by FadeMind** [archlinuxfr/package-query#128]
@f2404 this is normal result at the end?

**Foreign packages: \ 87 / 87**

IMO mark `\` is here useless
```
$ yaourt -Syua
:: Synchronizing package databases...
 testing is up to date
 core is up to date
 extra is up to date
 community-testing is up to date
 community is up to date
 infinality-bundle is up to date
 infinality-bundle-fonts is up to date
 Foreign packages: \ 87 / 87
```

**Comment by f2404** [comment]
@FadeMind I agree, it's absolutely useless.
But don't you think it's coming from yaourt?

**Comment by f2404** [comment]
Hmm, here's what I'm seeing: `Foreign packages: - 30 / 30`

**Comment by f2404** [comment]
It comes from https://github.com/archlinuxfr/yaourt/blob/master/src/lib/abs.sh.in#L177
Looks like a symbol is just randomly taken from the array: `bar="|/-\\"`. I cannot tell what's the purpose of this thing.

**Comment by larchunix** [comment]
IIUC, it is a progress indicator.

**Comment by f2404** [comment]
@larchunix Ah, that could be. But I don't see it's circling, it just appears after all packages are calculated.

**Comment by larchunix** [comment]
@f2404 I can see it circling in my case (I guess my computer is slow).

**Comment by f2404** [comment]
@larchunix  Ok, then it seems to be working as expected.
@FadeMind Are you happy with the resolution?

**Comment by FadeMind** [comment]
@f2404 @larchunix  thanks for explain. So...
![s](http://sd.keepcalm-o-matic.co.uk/i/keep-calm-it-s-not-a-bug-it-s-a-feature-5.png)
