### ISSUE TITLE
There's no way to get the "Build Date" for sync repo packages

### ISSUE THREAD

**Issue by Xavion** [archlinuxfr/package-query#140]
When I do a "pacman -Si <package>", one of the values returned is the "Build Date".  I can't seem to get this information from 'package-query' for some reason.

I tried using the "%L: last submission" format option, but that only works on AUR.  Can you please enable it on sync repos as well?  Right now, I keep getting a rather frustrating "-".

**Comment by Xavion** [comment]
Thanks - much appreciated.

**Comment by f2404** [comment]
Thanks for noticing this!
