### ISSUE TITLE
Can't install on arm due to pacman 5.2 dependency

### ISSUE THREAD

**Issue by Hinkiii** [archlinuxfr/package-query#145]
pacman-5.1.3-1.1 is the latest I can install

**Comment by f2404** [comment]
pacman 5.2.0-2 was released today: https://www.archlinux.org/packages/core/x86_64/pacman/
You could check your mirror and maybe switch to another one that's up-to-date.

**Comment by f2404** [comment]
Sorry, I overlooked that it's about arm. I guess you have to wait until 5.2.0 has been ported to your architecture.

**Comment by f2404** [comment]
If I go to https://archlinuxarm.org/packages and search for "pacman", 5.2.0 is there. I'm closing the issue.
