### ISSUE TITLE
Searching AUR broken

### ISSUE THREAD

**Issue by j00ch** [archlinuxfr/package-query#151]
After successfully building from this git and installing the program, i can't seem to get any results for AUR searches.
When i run:
`package-query -A package-quer`
I get no results

When i run:
`package-query -A package-query`
I get:
`aur/package-query 1.12-1 [installed] (1162) (0,21)`

Currently running version 1.12. GCC 12.1.0, pacman 6.0.1

Any hints?

**Comment by f2404** [comment]
You need to provide the "search" flag (-s): `package-query -A package-query`
