### ISSUE TITLE
Can't query AUR packages

### ISSUE THREAD

**Issue by LBlaboon** [archlinuxfr/package-query#18]
Not sure exactly when this started happening (probably within the last few days), but I just noticed that I can't query AUR packages anymore.

```
$ package-query -A package-query
AUR error : Invalid query arguments
```

I noticed this when attempting to do a system upgrade with yaourt, which prints the same error message while checking the AUR for updates.

Only the AUR is affected by this. Querying local/sync packages still works fine:

```
$ package-query -Q package-query
local/package-query 1.6.2-1
```

EDIT: Just noticed that the AUR was down for maintenance while I was performing those commands. However, the AUR is back up now and I'm still seeing the same issue.

**Comment by 9R** [comment]
Same problem here.
This is most likely related to changes in the new AUR version released today:

https://lists.archlinux.org/pipermail/aur-general/2015-October/031580.html

**Comment by FredBezies** [comment]
And it is breaking a lot of user setups. I reported a bug against yaourt and there is at least 7 or 8 people seeing this annoying bug... Which can be also verified in git version... :(

https://github.com/archlinuxfr/yaourt/issues/153

**Comment by Skunnyk** [comment]
A bug in rpc.php / multiinfo on AUR 4.1, see https://bugs.archlinux.org/task/46547?project=2

**Comment by Shamash2014** [comment]
I come to this bug after I install package with yaourt and suddenly close the terminal window. Than I can't install any package

**Comment by Skunnyk** [comment]
Fixed https://lists.archlinux.org/pipermail/aur-general/2015-October/031582.html

**Comment by LBlaboon** [comment]
Thanks for the update. Looks like it works now!

**Comment by Shamash2014** [comment]
Yep) Thanks for update)

2015-10-03 13:45 GMT+03:00 L. Bradley LaBoon <notifications@github.com>:
