### ISSUE TITLE
Add option to search packages only by name

### ISSUE THREAD

**Issue by f2404** [archlinuxfr/package-query#21]
Add an option to take into account only package names when searching (-s option). This is referred to yaourt issue 73 - "yaourt rar" not working.

**Comment by Skunnyk** [comment]
Fixed in #22 
Need to add support in yaourt now :)

Thanks !

**Comment by f2404** [comment]
Does yaourt support its own options, in addition to pacman's?
I'm asking because I can see pacman's help in yaourt output; and I'm not too close with the yaourt code yet.

**Comment by Skunnyk** [comment]
Yes, you can look at yaourt man page : "Since the majority of those options are the same as pacman’s (pacman(8)), this manual page will focus on the yaourt-specific ones."

**Comment by f2404** [comment]
I've created a PR for yaourt, please take a look.
