### ISSUE TITLE
format_str(char *s) crashes on some input strings

### ISSUE THREAD

**Issue by f2404** [archlinuxfr/package-query#24]
format_str(char *s) function from util.c crashes on some input strings like "str\\\\ning" - i.e. when the "\\\\" sequence is followed by one of the special chars: e, n, r, t.
I'm not sure how critical this issue is - what kind of strings can this function accept in reality?

**Comment by f2404** [comment]
A string like "string\\\\n" causes crash as well.
Seems like the function should be rewritten.

**Comment by djoby** [comment]
forgot to malloc maybe ?

**Comment by f2404** [comment]
No, it's that some pointer magic is not working...

**Comment by djoby** [comment]
humm wierd i cant reproduce your use case, can you provide a piece of code ?

**Comment by f2404** [comment]
@djoby I was running a kind of unit test on ideone: http://ideone.com/qy2qUL
The program on the link crashes.

**Comment by djoby** [comment]
sup' sorry for the late reply.
There s no malloc in your sample code.
Could you try with something like :
```C
int l = strlen("str\\n");
char *b = malloc(l);
bzero(b, l);
strcpy(b, "str\\n");

format_str(b);
free(b);
```

**Comment by f2404** [comment]
Yes, and it also works with char array: http://ideone.com/qy2qUL
I will close the issue, thanks.
