### ISSUE TITLE
An issue with pacman 4.2.0-6

### ISSUE THREAD

**Issue by KKRogers** [archlinuxfr/package-query#3]
Hi, everyone:
After upgrading to pacman 4.2.0-6, I get an issue "package-query: error while loading shared libraries: libalpm.so.8: cannot open shared object file: No such file or directory" when I use yaourt to install packages from aur.
BTW, I'm pretty sure this issue is linked with package-query! As I can use yaourt to install packages with pacman 4.1.2-7 and package-query 1.5-2.
Any help?
Thanks.

**Comment by tuxce** [comment]
package-query needs to be rebuilt because of a shared library version bump.

**Comment by KKRogers** [comment]
Thanks for reply.
I have no idea how to rebuild it. Do you mean I should reinstall yaourt and package-query?
Could you teach me in detail?

**Comment by tuxce** [comment]
You have to run makepkg again :

curl -O https://aur.archlinux.org/packages/pa/package-query/package-query.tar.gz
tar zxvf package-query.tar.gz
cd package-query
makepkg -si



2015-01-28 2:48 GMT+01:00 KKRogers <notifications@github.com>:

**Comment by cvkramer** [comment]
Link doesn't exist

**Comment by flaiker** [comment]
@cvkramer https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=package-query

**Comment by mariomenjr** [comment]
@CaledoniaProject Hello there. I am new in linux in general. Could you explain how to do that please?

**Comment by CaledoniaProject** [comment]
@mariomenjr If you're referring to the `package-query: error while loading shared libraries: libalpm.so.10` error, try `ln -sf /usr/lib64/libalpm.so.11 libalpm.so.10`

**Comment by f2404** [comment]
> try `ln -sf /usr/lib64/libalpm.so.11 /usr/lib64/libalpm.so.10`

@mariomenjr This is a terrible advice, never do that! `libalpm` has changed its soname which means it isn't backward-compatible with the previous version (`so.10`).
What you need to do is to rebuild `package-query` after you've upgraded `pacman` to version 5.1.0.

**Comment by f2404** [comment]
@CaledoniaProject What tests are you talking about? One of the libraries has changed its soname. This means any application that depends on it (including `package-query`) has to be rebuilt against the new library release. Since `package-query` isn't distributed in binary form, the burden of rebuilding it falls onto its users. There's nothing I can do for you.

**Comment by CaledoniaProject** [comment]
@f2404 Ah, make sense. I thought package-query is part of pacman, my bad

**Comment by mxinden** [comment]
Elaborating further on @f2404 reply for anyone like me:

1. Run: `pacman -Syu`
2. Download package-query: `curl -O https://aur.archlinux.org/cgit/aur.git/snapshot/package-query.tar.gz`
3. Unpack it: `tar -zxvf package-query.tar.gz`
4. Install it: `makepkg --install --syncdeps --rmdeps`

@f2404 Please correct me if I am wrong.

**Comment by tmmit** [comment]
@mxinden 's answer describes the way it worked seamlessly
