### ISSUE TITLE
curl: option -/extra.abs.tar.gz: is unknown curl: try 'curl --help' or 'curl --manual' for more information

### ISSUE THREAD

**Issue by FadeMind** [archlinuxfr/package-query#48]
I using lastest development snapshot. Normally  yaourt -G packagename download whole tarball from ABS and extract selected dir:
(standard output on stable release)
[tomasz@arch ~]$ export LANG=C
[tomasz@arch ~]$ yaourt -G gparted
==> Download gparted sources
x gparted.install
x PKGBUILD
x org.archlinux.pkexec.gparted.policy
x gparted_polkit
[tomasz@arch ~]$ 

After install lastest package-query-git and yaourt-git I get issue:

[tomasz@arch ~]$ yaourt -G krusader
==> Download krusader sources
==> community-testing/krusader: Download abs archive
**curl: option -/community-testing.abs.tar.gz: is unknown**
**curl: try 'curl --help' or 'curl --manual' for more information**

steps:
upgrade package-query-git > upgrade yaourt-git  > close and open new terminal window > type `yaourt -G gparted` (for example)
@Skunnyk  Regards

FadeMind

**Comment by Skunnyk** [comment]
Oh, yes, last package-query commit break that ! 
```
$ package-query --aur-url https://aur.archlinux.org -1Sif %u extra/gparted
-
```

Old behavior : 
```
$ package-query --aur-url https://aur.archlinux.org -1Sif %u extra/gparted
http://mir.archlinux.fr/extra/os/x86_64/gparted-0.23.0-1-x86_64.pkg.tar.xz
```

Ping @f2404 :)

**Comment by f2404** [comment]
Oh really? I will look into that.

**Comment by f2404** [comment]
@FadeMind Please verify the fix.

**Comment by FadeMind** [comment]
@f2404  @Skunnyk 

Patch from https://github.com/f2404/package-query/commit/f587b2bd425e4a4bc6fd85c60ec1a35f6e2c3d0f.patch
for package-query

FIXED ISSUE.
REF: https://github.com/archlinuxfr/package-query/pull/49

[tomasz@arch ~]$ export LANG=C
[tomasz@arch ~]$ yaourt -G git    
==> Download git sources
x PKGBUILD
x git-daemon@.service
x git.install
x git-daemon.socket
[tomasz@arch ~]$ pacman -Q|grep yaourt             
yaourt-git 1.7.22.g01f4706-1
[tomasz@arch ~]$ pacman -Q|grep package-q
package-query-git 1.7.58.g458953e-1
[tomasz@arch ~]$
