### ISSUE TITLE
Order when sorting results by votes?

### ISSUE THREAD

**Issue by f2404** [archlinuxfr/package-query#74]
Current, the vote numbers are increasing in the output - this means that the packages with the least numbers of votes come first, and the most voted packages are among the last.
Is this order correct? I mean, I'd rather expect seeing the "best" (most votes) packages first than having to scroll all the way down the screen.

The same question applies to the popularity sort - do the most popular packages appear first or last?
And to the relevance sort as well.

**Comment by larchunix** [comment]
I agree with you, most popular/relevant/voted packages should be displayed first.
