### ISSUE TITLE
aur-url is used twice

### ISSUE THREAD

**Issue by swiftgeek** [archlinuxfr/package-query#8]
aur-url is used twice, but i think it only happens since ~today  (Last time it worked was slightly past 2015-06-10 13:54, time from aur)
Example:
```
package-query --aur-url 'https://aur4.archlinux.org' -1Aif "%n %i %v %w %o %u %m %l %L" gputest
gputest 190320 0.7.0-1 18 0 https://aur4.archlinux.orghttps://aur4.archlinux.org/cgit/aur.git/snapshot/gputest.tar.gz swiftgeek 0.7.0-1 1433892021
```

**Comment by Skunnyk** [comment]
Yes, can reproduce, the rpc now return the URLPath again… https://lists.archlinux.org/pipermail/aur-dev/2015-June/003246.html

But with full domain :/ : 

Aur3:
"URLPath":"\/packages\/ya\/yaourt-git\/yaourt-git.tar.gz"
Aur4:
"URLPath":"https:\/\/aur4.archlinux.org\/cgit\/aur.git\/snapshot\/yaourt-git.tar.gz"

**Comment by swiftgeek** [comment]
Added 
```
        pkgurl=${pkgurl/https:\/\/aur4.archlinux.orghttps:\/\/aur4.archlinux.org/https:\/\/aur4.archlinux.org} # PACKAGE-QUERY workaround
```
before curl_fetch() in aur_get_pkgbuild() in aur.sh as workaround because i'm not so good with parsing strings in C

**Comment by Skunnyk** [comment]
Can you try with package-query-git ? (Not the best fix ever :])

**Comment by swiftgeek** [comment]
Actually very nice, except for enforcing https (but no idea if there exists ~~3rd~~ 4th party AUR)

**Comment by Skunnyk** [comment]
I only check if URLPath begin with "https" to try to differenciate AUR3 from AUR4 (see https://github.com/archlinuxfr/package-query/issues/8#issuecomment-111441241), there is no enforcing.
