### ISSUE TITLE
package-query cannot handle globs in Include

### ISSUE THREAD

**Issue by bebehei** [archlinuxfr/package-query#84]
I've got the following option in my pacman.conf file: `Include = /etc/pacman.d/options/*.conf`
The pacman.conf is according to the manpage correct and pacman works flawless.
```
$ man pacman.conf
[...]
       Include = path
           Include another configuration file. This file can include repositories or
           general configuration options. Wildcards in the specified paths will get
           expanded based on glob(7) rules.
[...]
```

But when I execute package-query
```
$ package-query [pkg]
Unable to open file: /etc/pacman.d/options/*.conf
$
```

After deleting the Include-line, it works correct.

**Comment by f2404** [comment]
Hi @bebehei 
This feature has been implemented in https://github.com/archlinuxfr/package-query/commit/7d1ae43c9f378459d17978fc021f3428260a6fb6
Are you using the git version of package-query?

**Comment by f2404** [comment]
And it's a dup of #38

**Comment by bebehei** [comment]
No, I'm not using the git-version of package-query. Personally, I don't see any good reason for this. I'd encourage you to release after features are ready. But that's just an esoteric aspect.

Sorry for the inconvenience. This is a hard facepalm and my fault. I should have searched through the closed ones, too.

**Comment by bebehei** [comment]
After browsing through the commit list, I can see, you made a bunch of work during the last months, @f2404. (very good :+1: ). I really would like to see a new release of this as it would honor your work, cause the others using package-query would get the goods of your it.

**Comment by f2404** [comment]
Thank you for your good words, @bebehei 
Unfortunately, I am not assigned to releasing package-query; @Skunnyk is the release guy, and he was actually going to make it. BTW, I think this is a good reason for using the git version :)
