### ISSUE TITLE
Compatibility with pacman 5.0

### ISSUE THREAD

**Issue by Skunnyk** [archlinuxfr/package-query#90]
Pacman 5.0 is out, in [testing] for now (see https://lists.archlinux.org/pipermail/arch-dev-public/2016-January/027732.html).

Just tried it on a VM, of course you need to recompile package-query to link to the new alpm version.

It seems to works, no compilation warnings and basic operations works (good news).

This issue in only to follow potential broken features in pacakge-query with pacman 5.0 :)

**Comment by f2404** [comment]
I've installed 5.0 and tested `package-query` with my test script (https://github.com/f2404/package-query-test) - all basic functions I've implemented the tests for seem to be working fine.

I'm not saying that nothing should be implemented or improved, though.

**Comment by gaydenko** [comment]
Hi! Pacman 5.0 is already in **official** repo. So what is the way to move on? :)

**Comment by f2404** [comment]
@gaydenko I can suggest a couple of options:
- install `package-query-git` and `yaourt-git` from AUR - `package-query` will get compiled against new `libalpm`, everything will work. I've taken this option myself;
- install `package-query` and `yaourt` from AUR - but modify `package-query`'s dependencies in PKGBUILD: `depends=('pacman>=4.1' 'yajl>=2.0')`.

**Comment by karkandcoypp** [comment]
@f2404 Thank you very much!!! It's works for me!

**Comment by hasamoder** [comment]
@f2404 Thanks - now I can install software needed for linux.conf.au presentation tomorrow :+1:

**Comment by f2404** [comment]
@karkandcoypp @hasamoder You are welcome, guys :)

**Comment by Emantor** [comment]
@f2404 I'd suggest changing the depends for method 2 to `depends=('pacman>=4.1' 'pacman<5.1' 'yajl>=2.0')`, future pacman updates won't break your package-query and yaourt then, as is the case with the switch to 5.0.

**Comment by f2404** [comment]
@Emantor Since my suggestion applies to the local PKGBUILD changes only, this really doesn't matter - the PKGBUILD won't be saved, and the future upgrades will again require it to be changed.

For the official package PKGBUILD update, however, your suggestion may and probably will be taken.

**Comment by Skunnyk** [comment]
I updated the package-query PKGBUILD on aur, hope all is good for now

**Comment by hasamoder** [comment]
Official fix now available on AUR. "aur/package-query 1.7-1 1 -> 2"

**Comment by z3ntu** [comment]
Close?

**Comment by z3ntu** [comment]
The aur package is broken

> package-query: error while loading shared libraries: libalpm.so.9: cannot open shared object file: No such file or directory

**Comment by f2404** [comment]
@z3ntu You need to reinstall the package after updating `pacman` to version 5.0.

**Comment by z3ntu** [comment]
I did.

**Comment by z3ntu** [comment]
I did.

> $ yaourt -Syu --aur
package-query: error while loading shared libraries: libalpm.so.9: cannot open shared object file: No such file or directory
:: Synchronizing package databases...
 core is up to date
 extra is up to date
 community is up to date
 multilib is up to date
package-query: error while loading shared libraries: libalpm.so.9: cannot open shared object file: No such file or directory

> package-query: error while loading shared libraries: libalpm.so.9: cannot open shared object file: No such file or directory

**Comment by f2404** [comment]
No - otherwise, `package-query` would be compiled against `libalpm.so.10` which is part of `pacman-5.0`.

**Comment by Emantor** [comment]
You can't update package-query with yaourt, because it needs package-query. Download the source tarball, run makepkg and install the new package-query.*.xz

**Comment by z3ntu** [comment]
Okay after recompiling several times it finally worked...

**Comment by f2404** [comment]
@z3ntu Great!

**Comment by f2404** [comment]
I guess the issue may be closed, right?

**Comment by z3ntu** [comment]
As it works, yes.

**Comment by f2404** [comment]
Fine, closing.

**Comment by Harleqin** [comment]
So now each time that pacman is updated so that libalpm gets a new version, yaourt breaks so that it needs manual package building to get running again?  There has to be a better way.

**Comment by f2404** [comment]
Can you suggest any better way?

**Comment by Harleqin** [comment]
Maybe communication through linking is not the right design choice here (wherever the responsibility for that lies).

Maybe package-query or yaourt can somehow guard its startup, so that upon encountering this issue it can at least give a helpful hint what to do.  This could be worthwhile because it is an issue that _must_ crop up every single time the libalpm version changes.

**Comment by f2404** [comment]
libalpm provides APIs for working with pacman databases. In order to be able to use those APIs, package-query is dynamically linked to libalpm.

The issue does not crop up every time libalpm version changes - it only does when libalpm's soname changes, which happens once in 2-2.5 years.
The problem with the soname change is that it means that new release is backward-incompatible with the previous one. Which implies rebuilding all dependent programs against the new library binary.

**Comment by aminnairi** [comment]
Solution from  @f2404 worked for me. I must have been lazy as I didn't merge the pacman.pacnew file before the upgrade. Might be the source of the issue.
